; Configuração Global (Deve ficar no topo)
[platformio]
src_dir = src

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    mathworks/ThingSpeak @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.4.3